# Generated by Django 3.0.8 on 2020-09-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Res1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='reslink',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
