# Generated by Django 3.0.8 on 2020-09-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Res1', '0002_hotel_reslink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=40, null=True, upload_to='')),
                ('desc', models.TextField(max_length=540, null=True)),
            ],
        ),
    ]
